variable "name" {}
variable "vpc_id" {}
variable "subnet_ids" {}
variable "security_group_ids" {}
variable "cluster_id" {}
variable "cluster_arn" {}
variable "execution_role_arn" {}
variable "listener_arn" {}
variable "dns_name" {}
